# Generated by Django 5.2.6 on 2025-09-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('gemini', 'Gemini AI'), ('openweather', 'OpenWeatherMap'), ('twilio', 'Twilio SMS')], max_length=20)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('tokens_used', models.IntegerField(blank=True, help_text='For AI APIs', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Usage Log',
                'verbose_name_plural': 'API Usage Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('heavy_rain', 'Heavy Rain'), ('drought_warning', 'Drought Warning'), ('frost_warning', 'Frost Warning'), ('high_wind', 'High Wind'), ('heatwave', 'Heatwave'), ('cyclone', 'Cyclone'), ('hail', 'Hail Storm'), ('flood', 'Flood Warning')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('weather_data', models.JSONField(help_text='Raw weather data that triggered this alert')),
                ('location_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('location_lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_sent_sms', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
