# Generated by Django 5.2.6 on 2025-09-16 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the transaction')),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Type of financial entry', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in INR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(help_text='Brief description of the transaction', max_length=200)),
                ('category', models.CharField(help_text='Category of income or expense', max_length=50)),
                ('crop_related', models.CharField(blank=True, help_text='Specific crop this transaction relates to', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('other', 'Other')], help_text='Method of payment', max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number (optional)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Ledger Entry',
                'verbose_name_plural': 'Financial Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
