# Generated by Django 5.2.6 on 2025-09-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the knowledge article', max_length=200)),
                ('content', models.TextField(help_text='Main content of the article')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of the article', null=True)),
                ('category', models.CharField(choices=[('crop_cultivation', 'Crop Cultivation'), ('pest_management', 'Pest Management'), ('soil_health', 'Soil Health'), ('irrigation', 'Irrigation'), ('fertilizers', 'Fertilizers'), ('weather_management', 'Weather Management'), ('post_harvest', 'Post Harvest'), ('marketing', 'Marketing'), ('government_schemes', 'Government Schemes'), ('organic_farming', 'Organic Farming'), ('livestock', 'Livestock'), ('general', 'General')], help_text='Category of the knowledge article', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', help_text='Language of the article', max_length=5)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for better searchability', max_length=200, null=True)),
                ('source', models.CharField(blank=True, help_text='Source or reference of the information', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this article should be included in searches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'indexes': [models.Index(fields=['category', 'language'], name='chatbot_kno_categor_cf75de_idx'), models.Index(fields=['is_active', 'language'], name='chatbot_kno_is_acti_245a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
                ('context_articles', models.ManyToManyField(blank=True, help_text='Knowledge articles used as context for this response', to='chatbot.knowledgearticle')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
