# Generated by Django 5.2.6 on 2025-09-16 13:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the activity')),
                ('activity_type', models.CharField(choices=[('sowing', 'Sowing'), ('fertilizing', 'Fertilizing'), ('watering', 'Watering'), ('harvesting', 'Harvesting'), ('pest_control', 'Pest Control'), ('weeding', 'Weeding'), ('pruning', 'Pruning'), ('irrigation', 'Irrigation'), ('other', 'Other')], help_text='Type of farming activity', max_length=20)),
                ('notes', models.TextField(help_text='Detailed notes about the activity')),
                ('crop_involved', models.CharField(blank=True, help_text='Specific crop involved in this activity', max_length=100, null=True)),
                ('area_covered', models.DecimalField(blank=True, decimal_places=2, help_text='Area covered in acres (optional)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weather_condition', models.CharField(blank=True, help_text='Weather condition during activity', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diary Entry',
                'verbose_name_plural': 'Diary Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.DecimalField(decimal_places=8, help_text='Latitude coordinate of the farm', max_digits=10, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('location_lon', models.DecimalField(decimal_places=8, help_text='Longitude coordinate of the farm', max_digits=11, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('primary_crops', models.CharField(help_text='Comma-separated list of primary crops', max_length=200)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], help_text='Primary soil type of the farm', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
            },
        ),
    ]
